CREATE TABLE ACCOUNT(
	ACCOUNT_ID INTEGER NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	ORIGINAL_VALUE NUMERIC(10,2) NOT NULL,
	EXPIRATION_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
	PAYMENT_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
	DAYS_DELAY INTEGER NOT NULL,
	FINED NUMERIC(10,2) NOT NULL,
	INTEREST NUMERIC(10,2) NOT NULL,
	
    PRIMARY KEY (ACCOUNT_ID)
);
CREATE SEQUENCE ACCOUNT_ID_SEQ START WITH 1;
